### ISSUE TITLE
Waddu Alpha 6 Bugfix Release 18 ?

### ISSUE THREAD

**Issue by lastdans** [Roemer/Waddu#12]
Hello Roemer.

I'm a waddu's user since you posted it on WoWACE and I thank you for your work!

You have release a new version with the changes of curseforge and wowace but, you didn't upload it on http://waddu.flauschig.ch/. Is it a choice?

I'm not aware of compiling source code or modifying it. And I would continue using Waddu instead of curse or minion. So, do you plain to update it on your page ?

(Sorry for my english)

**Comment by Sano** [comment]
I downloaded and compiled the latest update and the changes do not work.

**Comment by Roemer** [comment]
I will make a release of it. @Sano what happens? Any error?

**Comment by Talyrius** [comment]
CurseForge and WowAce have been completely redesigned.

**Comment by Roemer** [comment]
@Talyrius I know, I did some quick fixes, they work for me.

**Comment by Talyrius** [comment]
Sorry, I didn't realize. I just looked at it (7a71a03) and I noticed something unrelated. The CurseForge project URLs should start with "wow" instead of "www" to avoid conflicts with matching project names for other games like Minecraft.

**Comment by Sano** [comment]
I'm getting 404's.  Fiddler shows CurseForge redirecting to a non existent site.  CurseForge change the was it shows -nolib archives, so I think that is part of the issue.  I'm working on ParseInfoSite right now to see if I can come up with a solution.

**Comment by Sano** [comment]
I updated the CurseForge URLs to point as you suggested and got it partially working.  I had to change the GetFilePath to just return GetSiteAddon(mapping).FileUrl.  The "HTML" it was attempting to parse was the actual file itself and it was throwing Object ref error.  FWIW, I had already made the same change in WowAce.   I'll post a fork when I get a moment.

**Comment by Roemer** [comment]
cool, waiting for your PR then. Strange that it works for me.

**Comment by Sano** [comment]
PR posted.

**Comment by Roemer** [comment]
Thanks. I merged it and did a new release (also adjusted some mappings). If there are more problems, please open a new issue.
